version: "3.9"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports: ["5432:5432"]

  zookeeper:
    image: bitnami/zookeeper:3.9
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"

  kafka:
    image: bitnami/kafka:3.7.0      # rama LTS actual :contentReference[oaicite:0]{index=0}
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on: [zookeeper]
    ports: ["9092:9092"]

  spark-master:
    image: bitnami/spark:4.0.0      # Spark 4.0 GA may-2025 :contentReference[oaicite:1]{index=1}
    environment: { SPARK_MODE: master }
    ports: ["7077:7077","4040:4040"]

  spark-worker:
    image: bitnami/spark:4.0.0
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on: [spark-master]

  airflow:
    image: bitnami/airflow:3.0.0    # Airflow 3 GA abr-2025 :contentReference[oaicite:2]{index=2}
    environment:
      AIRFLOW_DATABASE_NAME: airflow
      AIRFLOW_DATABASE_USER: airflow
      AIRFLOW_DATABASE_PASSWORD: airflow
      AIRFLOW_EXECUTOR: LocalExecutor
      _PIP_ADDITIONAL_REQUIREMENTS: apache-airflow-providers-apache-spark
    volumes:
      - ./dags:/opt/airflow/dags
    ports: ["8080:8080"]
    depends_on: [postgres]

volumes:
  pg_data:
